---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pudim
  labels:
    k8s-app: pudim
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: pudim
  template:
    metadata:
      labels:
        k8s-app: pudim
        name: pudim
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: msfidelis/pudim:v0
          name: pudim
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512m"
---
kind: Service
apiVersion: v1
metadata:
  name: pudim
spec:
  selector:
    k8s-app: pudim
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: pudim.raj.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pudim
                port:
                  number: 80
