---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whois
  labels:
    k8s-app: whois
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: whois
  template:
    metadata:
      labels:
        k8s-app: whois
        name: whois
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: msfidelis/whois:v1
          name: whois
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 250
              memory: 512

---
kind: Service
apiVersion: v1
metadata:
  name: whois
spec:
  selector:
    k8s-app: whois
  ports:
    - protocol: TCP
      port: 8080
      name: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whois
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /whois
            pathType: Prefix
            backend:
              service:
                name: whois
                port:
                  number: 8080