version: '3'
services:

  postgres:
    image: postgres:12.2-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=poc
      - APP_DB_USER=poc
      - APP_DB_PASS=poc
      - APP_DB_NAME=poc
    networks:
      - postgres-compose-network

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ${HOME}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge